-- Archery.Services — Supabase schema
-- Run once in Supabase → SQL Editor → New query → paste → Run.
-- Safe to re-run (idempotent).

-- ─────────────── STORE / CONTENT ───────────────
create table if not exists products (
  id          bigint generated by default as identity primary key,
  name        text not null,
  brand       text default '',
  description text default '',
  price       numeric(10,2) not null default 0,   -- INR
  was         numeric(10,2),
  category    text default '',
  stock       int not null default 0,
  img_url     text,
  active      boolean not null default true,
  created_at  timestamptz default now()
);

create table if not exists tournaments (
  id bigint generated by default as identity primary key,
  name text not null, date date, location text default '',
  prize numeric(12,2) default 0, slots int default 0, registered int default 0,
  status text default 'open', active boolean not null default true
);

create table if not exists athletes (
  id bigint generated by default as identity primary key,
  name text not null, state text default '', discipline text default '',
  rank int, pb int, active boolean not null default true
);

create table if not exists jobs (
  id bigint generated by default as identity primary key,
  title text not null, org text default '', location text default '',
  type text default '', salary text default '', active boolean not null default true
);

create table if not exists knowledge (
  id bigint generated by default as identity primary key,
  title text not null, category text default '', level text default '',
  read_time text default '', excerpt text default '', body text default '',
  published boolean not null default true, active boolean not null default true
);

create table if not exists news (
  id bigint generated by default as identity primary key,
  title text not null, category text default '', date date,
  excerpt text default '', active boolean not null default true
);

create table if not exists profiles (
  id bigint generated by default as identity primary key,
  handle text unique, name text default '', headline text default '', location text default '',
  discipline text default '', bio text default '', pb int, rank int, events int default 0, years int default 0,
  links jsonb default '[]', achievements jsonb default '[]', experience jsonb default '[]', certifications jsonb default '[]',
  verified boolean default false, active boolean not null default true
);

-- ─────────────── INBOXES (public submissions, moderated in admin) ───────────────
create table if not exists registrations (
  id bigint generated by default as identity primary key,
  tournament_id bigint, tournament_name text default '',
  first_name text default '', last_name text default '',
  dob text, gender text, fed_number text, country text, discipline text, level text, club text,
  status text default 'pending', created_at bigint
);
create table if not exists reports (
  id bigint generated by default as identity primary key,
  type text default '', name text, email text, description text default '', urgency text,
  status text default 'open', created_at bigint
);
create table if not exists applications (
  id bigint generated by default as identity primary key,
  org_name text default '', org_type text, contact_name text, email text, phone text,
  status text default 'pending', created_at bigint
);
create table if not exists posts (
  id bigint generated by default as identity primary key,
  author text default 'Guest', category text default 'General', title text default '', body text default '',
  replies jsonb default '[]', likes int default 0, pinned boolean default false, active boolean not null default true,
  created_at bigint
);
create table if not exists chats (
  id bigint generated by default as identity primary key,
  name text default '', email text, status text default 'open', unread boolean default true,
  updated_at bigint, messages jsonb default '[]'
);

-- ─────────────── COMMERCE ───────────────
create table if not exists customers (
  id bigint generated by default as identity primary key,
  name text default '', email text, phone text, created_at timestamptz default now()
);

create table if not exists orders (
  id bigint generated by default as identity primary key,
  order_no text unique,
  customer_name text default '', customer_email text, customer_phone text,
  address_line1 text, address_line2 text, city text, state text, pincode text, country text default 'India',
  geo_lat double precision, geo_lng double precision, geo_accuracy double precision,
  delivery_type text default 'standard',          -- standard | sameday
  items jsonb not null default '[]',
  goods numeric(10,2) default 0, delivery_fee numeric(10,2) default 0,
  tax numeric(10,2) default 0, platform_fee numeric(10,2) default 0,
  total numeric(10,2) default 0, currency text default 'INR',
  payment_status text default 'pending',           -- pending | paid | failed | refunded
  payment_method text default 'razorpay',
  razorpay_order_id text, razorpay_payment_id text,
  status text default 'new',                        -- new | confirmed | packed | shipped | delivered | cancelled
  created_at timestamptz default now(), updated_at timestamptz default now()
);
create index if not exists orders_status_idx  on orders(status);
create index if not exists orders_created_idx on orders(created_at desc);
create index if not exists orders_payment_idx on orders(payment_status);

-- ─────────────── ANALYTICS (admin dashboard) ───────────────
create table if not exists analytics_events (
  id bigint generated by default as identity primary key,
  type text not null,                  -- pageview | add_to_cart | begin_checkout | purchase
  path text, order_id bigint references orders(id) on delete set null,
  value numeric(10,2), meta jsonb default '{}',
  geo_lat double precision, geo_lng double precision, geo_city text, geo_region text,
  ua text, referrer text, created_at timestamptz default now()
);
create index if not exists analytics_type_idx on analytics_events(type, created_at desc);

-- ─────────────── SINGLE-ROW CONFIG ───────────────
create table if not exists settings (id int primary key default 1, data jsonb not null default '{}');
create table if not exists stats    (id int primary key default 1, data jsonb not null default '{}');

insert into settings (id, data) values (1, '{
  "currency":"INR",
  "storeName":"Archery.Services",
  "taxRate":0.10,
  "platformFeeRate":0.05,
  "deliveryStandard":49,
  "deliverySameDay":149,
  "freeDeliveryThreshold":999,
  "sameDayEnabled":true,
  "maintenanceMode":false,
  "shopEnabled":true,
  "announcementActive":false,
  "announcementText":"",
  "heroImage":""
}') on conflict (id) do nothing;

insert into stats (id, data) values (1, '{"pageViews":0,"orders":0,"revenue":0}') on conflict (id) do nothing;

-- Seed a couple of products so the shop isn't empty (prices in INR)
insert into products (name, brand, description, price, was, category, stock, active) values
  ('Pro Recurve Bow 68" 36lbs', 'Olympic Line', 'Tournament-ready recurve with carbon limbs.', 28999, 33999, 'Recurve Bows', 12, true),
  ('Carbon Compound Bow 60lbs', 'Carbon Series', 'High let-off compound for field and target.', 47999, null, 'Compound Bows', 6, true),
  ('Aluminium Arrow Set (12)', 'Field Series', 'Straightness-matched aluminium arrows.', 3499, 3999, 'Arrows', 60, true),
  ('80cm Competition Target Face', 'Range Series', 'WA 10-ring target face, weatherproof.', 899, 1099, 'Targets', 200, true),
  ('Leather Finger Tab Pro', 'Club Series', 'Anatomical leather tab with spacer.', 1299, null, 'Accessories', 40, true)
on conflict do nothing;

-- NOTE on security: the API connects with the pooled Postgres service connection
-- (server-side only, never exposed to the browser), so Row Level Security is not
-- required for these tables. If you later use the Supabase anon key in the browser,
-- enable RLS and add policies before doing so.
