-- Archery.Services — migration 005
-- Full account model: real profiles linked to users, staff (employees) with
-- roles, seller accounts, and federation officers (president/secretary/
-- treasurer/executive) linked to an approved federation application.
-- Idempotent — safe to re-run.

-- ─────────────── CUSTOMERS: real profile ownership + 2FA + reset ───────────────
alter table profiles add column if not exists user_id bigint;
create index if not exists profiles_user_idx on profiles(user_id);

alter table users add column if not exists username text;
create unique index if not exists users_username_idx on users(lower(username)) where username is not null;

alter table users add column if not exists account_type text default 'customer';  -- customer | seller
alter table users add column if not exists business_name text;
alter table users add column if not exists gst_number text;
alter table users add column if not exists payout_upi text;
alter table users add column if not exists seller_status text;                    -- null | pending | approved | rejected

alter table users add column if not exists totp_secret text;                      -- base32; null = 2FA off
alter table users add column if not exists totp_enabled boolean default false;
alter table users add column if not exists backup_codes jsonb default '[]';       -- array of hashed one-time codes
alter table users add column if not exists reset_hash text;
alter table users add column if not exists reset_expires bigint;

-- ─────────────── STAFF (your employees — separate from customers) ───────────────
create table if not exists staff (
  id bigint generated by default as identity primary key,
  name text not null default '',
  username text not null,
  email text,
  pass text not null,                       -- scrypt salt:hash
  role text not null default 'support',     -- manager | editor | support
  totp_secret text, totp_enabled boolean default false, backup_codes jsonb default '[]',
  active boolean not null default true,
  created_by text,                          -- 'owner' or a staff username
  created_at timestamptz default now(),
  last_login timestamptz
);
create unique index if not exists staff_username_idx on staff(lower(username));

-- ─────────────── FEDERATION OFFICERS ───────────────
-- Links a user account to an approved federation application with an office.
create table if not exists federation_members (
  id bigint generated by default as identity primary key,
  application_id bigint references applications(id) on delete cascade,
  user_id bigint references users(id) on delete cascade,
  office text not null,                      -- president | secretary | treasurer | executive_member
  added_at timestamptz default now(),
  unique(application_id, user_id)
);
create index if not exists fedmembers_app_idx on federation_members(application_id);
create index if not exists fedmembers_user_idx on federation_members(user_id);

-- ─────────────── SELLER PRODUCT OWNERSHIP ───────────────
alter table products add column if not exists seller_id bigint;
create index if not exists products_seller_idx on products(seller_id);
