-- Archery.Services — migration 007
-- THREAT_MODEL T5: the most privileged account had the least protection.
--   • /api/admin/login accepted unlimited guesses (no rate limit anywhere)
--   • the owner authenticated with a single master password and NO 2FA,
--     while staff accounts had TOTP
-- Idempotent. Run after 006.

-- ─────────────── RATE LIMITING (serverless has no shared memory) ───────────────
-- Every auth attempt is recorded so a limiter can count failures per IP and per
-- identity across instances. Also doubles as the security audit trail for logins.
create table if not exists login_attempts (
  id          bigint generated by default as identity primary key,
  key         text        not null,     -- 'ip:203.0.113.7' | 'id:owner' | 'id:priya'
  identity    text,                     -- who was being attempted (for forensics)
  ok          boolean     not null default false,
  ip          text,
  ua          text,
  created_at  timestamptz not null default now()
);
create index if not exists login_attempts_key_idx on login_attempts(key, created_at desc);
create index if not exists login_attempts_created_idx on login_attempts(created_at desc);

-- ─────────────── OWNER 2FA ───────────────
-- Single row (id=1). Kept in its OWN table, never in `settings`: /api/settings is
-- public, and a TOTP secret there would be world-readable.
create table if not exists owner_security (
  id            int primary key default 1,
  totp_secret   text,
  totp_enabled  boolean not null default false,
  backup_codes  jsonb   not null default '[]',
  updated_at    timestamptz default now(),
  constraint owner_security_singleton check (id = 1)
);
insert into owner_security (id) values (1) on conflict (id) do nothing;
