-- Archery.Services — migration 008
-- THREAT_MODEL T6 / CLAUDE.md §1.6: "Money is never trusted from the client.
-- Webhooks are the source of truth for payment state, not browser callbacks."
--
-- Before this migration the ONLY thing that ever marked an order paid was
-- /api/razorpay/verify — a call made by the customer's browser after checkout.
-- The signature check there is real, so this was not forgeable; the defect is
-- that it is not RELIABLE. If the customer closes the tab, loses signal, or the
-- redirect fails, Razorpay has the money and our order sits at 'pending'
-- forever. Nobody is told. That is the "real money in stuck pending orders"
-- problem.
--
-- Idempotent. Run after 007.

-- ─────────────── WEBHOOK IDEMPOTENCY ───────────────
-- Razorpay retries a webhook until it gets a 2xx, so the same event WILL arrive
-- more than once. Every delivery is recorded under its provider event id; the
-- handler refuses to process an id it has already completed. Without this, a
-- retry of payment.captured would decrement stock a second time.
create table if not exists webhook_events (
  id            bigint generated by default as identity primary key,
  provider      text not null default 'razorpay',
  event_id      text not null,                 -- x-razorpay-event-id
  event         text,                          -- payment.captured | order.paid | ...
  payload       jsonb,
  signature_ok  boolean not null default false,
  processed     boolean not null default false,
  error         text,
  received_at   timestamptz default now(),
  processed_at  timestamptz
);
-- The idempotency key. A retry hits this and is short-circuited.
create unique index if not exists webhook_events_uniq
  on webhook_events(provider, event_id);
create index if not exists webhook_events_received_idx
  on webhook_events(received_at desc);

-- ─────────────── ORDER LOOKUP BY RAZORPAY ID ───────────────
-- Both the webhook and the verify callback look an order up by its Razorpay
-- order id. There was no index: every payment did a sequential scan of orders.
create index if not exists orders_rzp_order_idx on orders(razorpay_order_id);
create index if not exists orders_rzp_payment_idx on orders(razorpay_payment_id);

-- ─────────────── PAYMENT FACTS ───────────────
-- What Razorpay actually told us, kept separately from what we asked for, so a
-- mismatch is detectable instead of silently accepted.
alter table orders add column if not exists amount_paid    numeric(10,2);
alter table orders add column if not exists paid_at        timestamptz;
alter table orders add column if not exists payment_source text;   -- webhook | callback | reconcile
alter table orders add column if not exists payment_notes  text;   -- e.g. amount mismatch detail

-- Reconciliation needs to find candidates cheaply: orders still pending that
-- have a Razorpay order id (i.e. checkout started and money may have moved).
create index if not exists orders_pending_rzp_idx
  on orders(payment_status, created_at desc)
  where razorpay_order_id is not null;
