-- Archery.Services — migration 009
-- THREAT_MODEL T7 / ADR-0008: "AI is a thin, metered, authenticated layer over
-- our own data. Server-held history. Sonnet default."
--
-- /api/coach was an anonymous, uncapped, forgeable, Opus-priced endpoint on our
-- card: no auth, no rate limit, no spend cap, and the "conversation" was
-- whatever the caller's browser said it was.
--
-- Idempotent. Run after 008.

-- ─────────────── SERVER-HELD CONVERSATIONS ───────────────
-- ADR-0008(5): "Client-supplied history is never trusted. The client sends a
-- conversation ID and a message; the server owns the transcript."
-- Trusting b.history let a caller forge assistant turns — i.e. put words in the
-- model's mouth to redirect it — while we paid for the tokens.
create table if not exists coach_conversations (
  id          bigint generated by default as identity primary key,
  user_id     bigint not null references users(id) on delete cascade,
  title       text,
  created_at  timestamptz default now(),
  updated_at  timestamptz default now()
);
create index if not exists coach_conv_user_idx on coach_conversations(user_id, updated_at desc);

create table if not exists coach_messages (
  id              bigint generated by default as identity primary key,
  conversation_id bigint not null references coach_conversations(id) on delete cascade,
  role            text not null check (role in ('user','assistant')),
  content         text not null,
  created_at      timestamptz default now()
);
create index if not exists coach_msg_conv_idx on coach_messages(conversation_id, created_at);

-- ─────────────── METERING ───────────────
-- ADR-0008(3): "A spend cap — per user, per day, and a global kill-switch. Track
-- cost per call." Cost is stored in paise to avoid float drift, and computed
-- server-side from the model's real token counts — never estimated in the client.
create table if not exists ai_usage (
  id              bigint generated by default as identity primary key,
  user_id         bigint references users(id) on delete set null,
  conversation_id bigint references coach_conversations(id) on delete set null,
  model           text not null,
  input_tokens    integer not null default 0,
  output_tokens   integer not null default 0,
  cost_paise      integer not null default 0,
  ok              boolean not null default true,
  created_at      timestamptz default now()
);
create index if not exists ai_usage_user_day_idx on ai_usage(user_id, created_at desc);
create index if not exists ai_usage_day_idx on ai_usage(created_at desc);

-- ─────────────── CAPS + KILL SWITCH ───────────────
-- Its OWN table, deliberately NOT `settings`: /api/settings is public, and the
-- `settings` table is a single jsonb blob served to anonymous browsers. Our
-- spend limits are not something to publish. (Same reasoning as owner_security
-- in migration 007.)
--
-- In a table rather than env vars so the kill switch can be thrown without a
-- deploy — at 03:00, mid-incident, by someone who is not holding a laptop.
create table if not exists ai_config (
  id                     int primary key default 1,
  enabled                boolean not null default true,
  daily_cap_paise_user   integer not null default 5000,     -- ₹50 / user / day
  daily_cap_paise_total  integer not null default 200000,   -- ₹2000 / day, platform-wide
  model                  text    not null default 'claude-sonnet-5',
  updated_at             timestamptz default now(),
  constraint ai_config_singleton check (id = 1)
);
insert into ai_config (id) values (1) on conflict (id) do nothing;
