-- Archery.Services — migration 010
-- Public "Team" section: the real people running the platform.
--
-- Deliberately a TABLE the owner fills in, not hardcoded names in about.html.
-- CLAUDE.md §1.1 forbids inventing data, and a team page is the single easiest
-- place to accidentally ship fiction ("Meet our team of 40 experts"). Nobody is
-- listed here until a real person is entered in the admin panel, and the public
-- section stays hidden while the table is empty.
--
-- NOT the `staff` table: that holds ADMIN LOGIN ACCOUNTS (username, password
-- hash, TOTP secret, role). Those are credentials and must never be published.
-- This is a separate, purely public-facing profile list.
--
-- Idempotent. Run after 009.

create table if not exists team (
  id          bigint generated by default as identity primary key,
  name        text not null,
  role        text default '',          -- e.g. "Founder", "Head Coach"
  bio         text default '',
  img_url     text,                     -- data URL or hosted image
  link        text,                     -- optional public profile / LinkedIn
  sort_order  int default 100,          -- lower shows first
  active      boolean default true,
  created_at  timestamptz default now()
);

create index if not exists team_order_idx on team(active, sort_order, id);
