-- Archery.Services — migration 013
-- Real clubs + club members. The first actual FEATURE behind the organisation
-- tiers, replacing bullet points that charged money for nothing.
--
-- Context: the club/district/state/national tiers advertised member management,
-- scheduling, attendance, rankings, etc. An audit (2026-07-22) found ZERO of
-- them implemented, so checkout-fee.js was set to refuse all org payments
-- (FOR_SALE = empty). This migration ships the first two real capabilities —
-- a club directory and admin-managed membership — so a pilot club can be
-- onboarded FOR FREE and the feature proven before any tier is put back on sale.
-- Do NOT re-enable a paid tier off the back of this alone: two of seven
-- advertised features is still not a tier worth charging for (§1.1, §1.6).
--
-- ⚠ DPDP / CLAUDE.md §1.8 — club_members deliberately stores NO date of birth
-- and NO age_class. Recording a minor's data triggers age-assurance and
-- verifiable parental-consent duties (DPDP s.9(3)) that this slice does not
-- implement. Adding under-18 archers is a separate, gated future slice. Do not
-- "helpfully" add a dob/age column here.
--
-- Idempotent, forward-only (ADR-0002). Run after 012 with `node supabase/apply.js`.

create table if not exists clubs (
  id             bigint generated by default as identity primary key,
  name           text not null,
  city           text default '',
  region         text default '',    -- continent bucket: Asia|Europe|Americas|Oceania|Africa
  country        text default '',
  discipline     text default '',    -- primary focus: recurve|compound|barebow|field|3d|traditional
  about          text default '',    -- public description
  email          text,               -- public contact
  phone          text,
  website        text,
  img_url        text,               -- logo/photo (data URL or hosted image)
  application_id bigint references applications(id) on delete set null,  -- provenance; nullable, set only by a controlled path
  active         boolean not null default true,   -- single visibility flag (matches the crud.js public filter)
  created_at     timestamptz default now()
);
create index if not exists clubs_public_idx on clubs(active, country, id);

create table if not exists club_members (
  id          bigint generated by default as identity primary key,
  club_id     bigint not null references clubs(id) on delete cascade,
  user_id     bigint references users(id) on delete set null,  -- linked platform account (future); null for roster-only entries
  name        text not null,
  email       text,
  discipline  text default '',                    -- division: recurve|compound|barebow (§3)
  member_role text not null default 'archer',     -- archer|coach|official
  status      text not null default 'active',     -- active|inactive
  added_at    timestamptz default now(),
  -- A linked account appears at most once per club. NULL user_id rows (roster
  -- entries with no platform account) are exempt from the constraint by SQL's
  -- NULL semantics, so many name-only members per club are allowed.
  unique (club_id, user_id)
);
create index if not exists club_members_club_idx on club_members(club_id, status, id);
create index if not exists club_members_user_idx on club_members(user_id);
