-- Archery.Services — migration 016
-- The audit log CLAUDE.md §1.5 requires and no handler in this codebase has
-- ever written to: "Every mutation writes an audit row — actor, action,
-- target, before/after, timestamp, IP. No exceptions. This is a product
-- feature, not plumbing: federations buy it."
--
-- Grep across api/ before this migration found zero audit_log table and zero
-- audit-writing code anywhere — every admin mutation (staff accounts, seller
-- approval, order status, settings) has been unlogged since the platform's
-- first commit. This is the real table; api/_lib/audit.js (added alongside
-- this migration) is the one shared writer every handler should call.
--
-- `before`/`after` are jsonb snapshots of the changed fields only, never a
-- full row dump — a staff row's password hash must never land in an audit
-- row readable by anyone with audit-log access, which may be a wider
-- audience than staff-management access.
--
-- Idempotent, forward-only (ADR-0002).

create table if not exists audit_log (
  id            bigint generated by default as identity primary key,
  actor_role    text,               -- 'owner' | 'manager' | 'editor' | 'support' | null (unauthenticated actions never reach this table)
  actor_id      text,               -- staff.id as text, or 'owner' (owner has no staff row)
  actor_name    text,
  action        text not null,      -- 'create' | 'update' | 'delete' | 'status_change'
  resource_type text not null,      -- table/resource name, e.g. 'staff', 'sellers', 'orders', 'settings'
  resource_id   text,               -- null only for singleton resources like settings
  before        jsonb,
  after         jsonb,
  ip            text,
  created_at    timestamptz not null default now()
);
create index if not exists audit_log_resource_idx on audit_log(resource_type, resource_id, created_at desc);
create index if not exists audit_log_created_idx   on audit_log(created_at desc);
