-- Archery.Services — migration 021
-- The core scoring domain: arrows, not scores. Every fact here is cited to
-- docs/DOMAIN.md, which in turn cites World Archery Rulebook, Book 3 —
-- Target Archery, version 2026-01-27. Do not add a rule here that isn't in
-- DOMAIN.md; if you need one that isn't, fetch the rulebook and update
-- DOMAIN.md first (CLAUDE.md §6: "verify, don't assume").
--
-- Scope of this migration (DOMAIN.md §8 flags several items as "ask, don't
-- guess" — these are deliberately NOT implemented here, not silently
-- guessed through):
--   - Field & 3D archery (Book 4) — rules not yet sourced.
--   - Para classification pathway — rules not yet sourced. `categories`
--     below has a para_class column so the shape exists, but no
--     classification workflow is built.
--   - Closest-to-centre measurement (Art. 12.5.2.2) for shoot-off ties:
--     DOMAIN.md leaves the capture method open (coordinates vs a judged
--     measurement event). Implemented here as a judged fact — an arrow can
--     carry optional x/y coordinates when a capture method exists, but the
--     tie is always resolved by an explicit judge decision recorded on the
--     end (closest_to_centre_side), matching the existing project
--     philosophy that an arrow's value is "an adjudicated fact, not a
--     sensor reading" (DOMAIN.md §3.1). This is a real, working default,
--     not a placeholder — but it's a judgement call worth a federation
--     technical delegate's review before Phase 2 sign-off, per DOMAIN.md's
--     own stated audience.
--   - Ianseo interop, full athlete/licence model — real follow-on work,
--     out of scope here. New tables reference the EXISTING athletes(id)
--     rather than replacing that table, so nothing already working breaks.

-- ─────────────── CATEGORIES: division × gender × age_class × para_class ───────────────
-- "This is the unit for entries, results, brackets and rankings." (DOMAIN.md §5)
create table if not exists categories (
  id          bigint generated by default as identity primary key,
  division    text not null check (division in ('recurve','compound','barebow')),
  gender      text not null check (gender in ('men','women','mixed')),
  age_class   text not null check (age_class in ('u15','u18','u21','senior','master50')),
  para_class  text check (para_class in ('W1','Open','VI1','VI2','VI3')),  -- null = able-bodied
  unique (division, gender, age_class, para_class)
);

-- ─────────────── EVENTS: a competition ───────────────
create table if not exists events (
  id                 bigint generated by default as identity primary key,
  tournament_id      bigint references tournaments(id) on delete set null,
  name               text not null,
  sanctioning_body   text,
  wa_ranking_group   int check (wa_ranking_group between 1 and 5),
  venue              text,
  starts_on          date,
  ends_on            date,
  created_at         timestamptz not null default now()
);

-- event_categories: which categories compete at this event, and the round
-- configuration that drives scoring format and tiebreak rule (DOMAIN.md
-- §3.3 "format is a function of division × team type"; §3.4 tiebreak
-- depends on distance_band).
create table if not exists event_categories (
  id               bigint generated by default as identity primary key,
  event_id         bigint not null references events(id) on delete cascade,
  category_id      bigint not null references categories(id),
  round_name       text,                    -- e.g. 'WA 70m Qualification'
  distance_m       numeric,
  distance_band    text check (distance_band in ('long','short')),  -- Art. 12.5.1
  face_size_cm     int,
  arrows_per_end   int not null default 6 check (arrows_per_end in (3,6)),
  created_at       timestamptz not null default now(),
  unique (event_id, category_id, round_name)
);

-- entries: an athlete entered in a category at this event.
-- References the EXISTING athletes table — full licence/category model is
-- separate follow-on work (DOMAIN.md §7), not blocking the scoring engine.
create table if not exists entries (
  id                    bigint generated by default as identity primary key,
  event_category_id     bigint not null references event_categories(id) on delete cascade,
  athlete_id            bigint not null references athletes(id),
  target_assignment     text,
  qual_rank             int,
  created_at            timestamptz not null default now(),
  unique (event_category_id, athlete_id)
);

-- ─────────────── MATCHES: qualification round, elimination match, or final ───────────────
-- format is stored explicitly per DOMAIN.md §3.3 — "a single match table
-- with one format is wrong" was about hardcoding one format for everything;
-- storing it per-row is the fix, not a second table per format.
create table if not exists matches (
  id                  bigint generated by default as identity primary key,
  event_category_id   bigint not null references event_categories(id) on delete cascade,
  kind                text not null check (kind in ('qualification','elimination','final')),
  format              text not null check (format in ('set','cumulative')),  -- Art. 12.1.4
  team_type           text not null default 'individual' check (team_type in ('individual','team','mixed_team')),
  bracket_position    text,             -- e.g. '1v64', null for qualification
  target_points_to_win int,              -- 6 individual set-play, 5 team set-play (Art 12.1.4.1/.2); null for cumulative
  ends_to_play        int,              -- 5 individual cumulative, 4 team cumulative (Art 12.1.4.3/.4); null for set-play
  status               text not null default 'scheduled' check (status in ('scheduled','live','done')),
  winner_match_entry_id bigint,          -- filled once resolved (fk added below, after match_entries exists)
  created_at           timestamptz not null default now()
);

-- match_entries: one row per participant side in a match (side 1 or 2 for
-- match play; side 1 only for a qualification "match" representing one
-- archer's round). Scores are NEVER stored here — always computed from
-- arrows (DOMAIN.md §1: "A score is a SUM... nobody can copy it, because
-- they didn't collect the arrows").
create table if not exists match_entries (
  id         bigint generated by default as identity primary key,
  match_id   bigint not null references matches(id) on delete cascade,
  side       smallint not null check (side in (1,2)),
  entry_id   bigint not null references entries(id),
  created_at timestamptz not null default now(),
  unique (match_id, side, entry_id)
);

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'matches_winner_fk') then
    alter table matches add constraint matches_winner_fk
      foreign key (winner_match_entry_id) references match_entries(id) on delete set null;
  end if;
end $$;

-- ends: a group of arrows scored together (Art. 12.1.2 — scoring happens
-- after each end/set). Belongs to one match_entry (one participant's end).
create table if not exists ends (
  id                        bigint generated by default as identity primary key,
  match_entry_id            bigint not null references match_entries(id) on delete cascade,
  end_number                int not null,
  is_shootoff               boolean not null default false,  -- Art. 12.5.2.2 "successive single arrow shoot-offs"
  shootoff_sequence         int,
  -- Art. 12.5.2.2 closest-to-centre: an explicit judge decision, not an
  -- auto-computed one (see migration header). true = this end's arrow(s)
  -- were judged closer to centre than the opposing side's shoot-off arrow.
  judged_closest_to_centre  boolean,
  judge                     text,        -- Art. 12.1.3: disagreement resolved by the judge
  client_id                 text,        -- offline-first idempotency key (ADR-0006)
  created_at                timestamptz not null default now(),
  unique (match_entry_id, end_number, shootoff_sequence)
);
create unique index if not exists ends_client_idx on ends(client_id) where client_id is not null;

-- arrows: THE atomic unit. APPEND-ONLY. A correction is a NEW row that
-- supersedes the old one, carrying a reason and an actor — never an
-- overwrite (ADR-0007, DOMAIN.md §3.1 "an arrow's value is an adjudicated
-- fact... corrections must be events with a reason").
create table if not exists arrows (
  id                  bigint generated by default as identity primary key,
  end_id              bigint not null references ends(id) on delete cascade,
  sequence            int not null,               -- recording order within the end
  value               smallint not null check (value between 0 and 10),
  is_x                boolean not null default false,
  is_miss             boolean not null default false,
  x_coord             numeric,
  y_coord             numeric,
  client_id           text,                          -- offline-first idempotency key
  superseded_by       bigint references arrows(id),
  correction_reason   text,
  actor               text,
  created_at          timestamptz not null default now(),
  constraint arrows_x_implies_ten check (not is_x or value = 10),
  constraint arrows_miss_implies_zero check (not is_miss or value = 0)
);
create unique index if not exists arrows_client_idx on arrows(client_id) where client_id is not null;
create index if not exists arrows_end_idx on arrows(end_id);

-- ─────────────── RANKINGS (DOMAIN.md §4) ───────────────
create table if not exists ranking_results (
  id                  bigint generated by default as identity primary key,
  athlete_id          bigint not null references athletes(id),
  event_category_id   bigint not null references event_categories(id),
  final_position      int not null,
  base_points         numeric not null,
  position_pct        numeric not null,
  period_multiplier   numeric not null default 1,
  ranking_score       numeric not null,
  earned_at           timestamptz not null default now()
);
create table if not exists ranking_lists (
  id            bigint generated by default as identity primary key,
  category_id   bigint not null references categories(id),
  published_at  timestamptz not null default now()
);
create table if not exists ranking_entries (
  id                    bigint generated by default as identity primary key,
  ranking_list_id       bigint not null references ranking_lists(id) on delete cascade,
  athlete_id            bigint not null references athletes(id),
  added_ranking_score   numeric not null,   -- sum of best 7 results
  rank                  int not null
);

create index if not exists entries_event_cat_idx on entries(event_category_id);
create index if not exists matches_event_cat_idx on matches(event_category_id);
create index if not exists match_entries_match_idx on match_entries(match_id);
create index if not exists ends_match_entry_idx on ends(match_entry_id);
