-- Archery.Services — migration 024
-- Real capability model for PLATFORM MEMBERS (athletes, coaches, officials) —
-- distinct from the STAFF model in migration 006 (staff = your employees).
-- CLAUDE.md §1.4: "every write endpoint is authorised by capability, not by
-- 'is logged in'... default deny." The design principle throughout this file:
-- a self-declared label never grants a capability that touches someone
-- else's data or a competition record. Every elevated capability here comes
-- from either (a) mutual consent between the two accounts involved, or
-- (b) an explicit staff approval — never from a field the user sets on
-- themselves.

-- A user's self-declared archery role. This is a LABEL — it drives which UI
-- a member sees and which requests they can initiate (a 'coach' can send a
-- coach-link request; an 'official' can request certification). It grants
-- NO capability by itself. Real capability always comes from one of the
-- tables below.
alter table users add column if not exists member_role text check (member_role in ('athlete','coach','official'));

-- Links a real account to their row in the athletes directory, so a signed-in
-- athlete can see their own scoring history and register themselves for
-- events. One user <-> one athletes row. Nullable — most historical/imported
-- athletes rows have no account at all, and that's fine.
alter table athletes add column if not exists user_id bigint references users(id) on delete set null;
create unique index if not exists athletes_user_idx on athletes(user_id) where user_id is not null;

-- A request to link a user account to an EXISTING athletes row ("claim my
-- profile"). Brand-new athletes rows created by a self-service signup don't
-- need this (see api/_handlers/members.js 'become-athlete') — this table
-- exists specifically because claiming a PRE-EXISTING named row (which could
-- belong to a real, unrelated person) must never be instant self-service.
create table if not exists athlete_claim_requests (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  athlete_id bigint not null references athletes(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  reviewed_by text,
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);
-- Only one OPEN claim per athlete at a time — a partial index (not a plain
-- unique constraint) so multiple past rejected claims on the same athlete
-- can coexist; only 'pending' is exclusive.
create unique index if not exists athlete_claim_pending_idx on athlete_claim_requests(athlete_id) where status = 'pending';
create index if not exists athlete_claim_user_idx on athlete_claim_requests(user_id);

-- Coach <-> athlete relationship. Requires an explicit accept from whichever
-- side did NOT initiate the request — a coach can never self-grant
-- visibility into an athlete's data, and an athlete is never silently
-- "claimed" by a coach.
create table if not exists coach_athletes (
  id bigint generated by default as identity primary key,
  coach_user_id bigint not null references users(id) on delete cascade,
  athlete_id bigint not null references athletes(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','active','revoked')),
  requested_by text not null check (requested_by in ('coach','athlete')),
  created_at timestamptz not null default now(),
  responded_at timestamptz,
  unique(coach_user_id, athlete_id)
);
create index if not exists coach_athletes_coach_idx on coach_athletes(coach_user_id);
create index if not exists coach_athletes_athlete_idx on coach_athletes(athlete_id);

-- Judge / technical delegate certification. Starts 'pending' on
-- self-declaration; only staff (owner/manager) can move it to 'approved'.
-- Levels are platform-defined administrative tiers, not a World Archery
-- citation — DOMAIN.md §8 flags officiating/classification pathways as
-- unsourced, so this is documented here as platform policy, not a rule.
create table if not exists official_certifications (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  level text not null default 'club' check (level in ('club','state','national','international')),
  issuing_body text,
  status text not null default 'pending' check (status in ('pending','approved','revoked')),
  approved_by text,
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  unique(user_id)
);

-- Per-event judge assignment. An approved official can only score matches at
-- an event they are actually assigned to — matching real competition
-- practice, and keeping "certified somewhere" from silently becoming
-- "can edit every match on the platform."
create table if not exists event_officials (
  id bigint generated by default as identity primary key,
  event_id bigint not null references events(id) on delete cascade,
  user_id bigint not null references users(id) on delete cascade,
  role text not null default 'judge' check (role in ('judge','technical_delegate','chief_judge')),
  assigned_by text,
  created_at timestamptz not null default now(),
  unique(event_id, user_id)
);
create index if not exists event_officials_event_idx on event_officials(event_id);
create index if not exists event_officials_user_idx on event_officials(user_id);
