-- Archery.Services — migration 025
-- Selection: choosing athletes for a squad/team from the platform's OWN
-- published ranking (ranking_lists/ranking_entries, migration 021/022) —
-- never a hand-typed list. A selection is generated FROM a real published
-- ranking list, snapshotted at generation time (append-only philosophy,
-- same as arrows/ends — DOMAIN.md §1), and staff can override an
-- algorithmic pick only with a recorded reason, never silently.

create table if not exists selections (
  id                bigint generated by default as identity primary key,
  category_id       bigint not null references categories(id),
  ranking_list_id   bigint references ranking_lists(id),  -- the published list this was generated from
  name              text not null,
  size              int not null check (size > 0),
  finalized         boolean not null default false,
  created_by        text,
  created_at        timestamptz not null default now()
);

create table if not exists selection_entries (
  id                    bigint generated by default as identity primary key,
  selection_id          bigint not null references selections(id) on delete cascade,
  athlete_id            bigint not null references athletes(id),
  rank_at_selection     int not null,       -- snapshot of ranking_entries.rank when generated
  score_at_selection    numeric not null,   -- snapshot of ranking_entries.added_ranking_score
  included              boolean not null default true,
  override_reason       text,               -- required whenever a staff action flips `included`
  overridden_by         text,
  overridden_at         timestamptz,
  unique(selection_id, athlete_id)
);
create index if not exists selection_entries_selection_idx on selection_entries(selection_id);
