-- Archery.Services — migration 026
-- Federation hierarchy: a real tree (national -> state -> district), not
-- just a flat, unstructured `applications` inbox row. This is
-- ORGANISATIONAL infrastructure only — it is deliberately UNRELATED to
-- api/_handlers/checkout-fee.js's district/state/national PAID tiers,
-- which remain switched off (FOR_SALE is an intentionally empty set,
-- documented there 2026-07-22, citing CLAUDE.md §1.1/§1.6 after a prior
-- audit found the platform charging for federation-portal features that
-- did not exist). Building this table does not reactivate billing for any
-- tier and must not be treated as doing so — that remains a business
-- decision, made deliberately, one feature at a time, per that file's
-- own comment.
--
-- tier reuses the exact vocabulary already used in federation.html's
-- (currently non-charging) registration form: district | state | national.

create table if not exists federations (
  id              bigint generated by default as identity primary key,
  name            text not null,
  tier            text not null check (tier in ('district','state','national')),
  parent_id       bigint references federations(id) on delete set null,
  region          text,                     -- free text (state/district name) — India-first, not a hardcoded enum
  application_id  bigint references applications(id) on delete set null,  -- provenance, same pattern as clubs.application_id
  active          boolean not null default true,
  created_at      timestamptz not null default now()
);
create index if not exists federations_parent_idx on federations(parent_id);

-- A national federation has no parent; state/district federations should.
-- Not a CHECK constraint (parent may be assigned after creation while an
-- application is still being reviewed) — enforced in the API instead.

alter table clubs add column if not exists federation_id bigint references federations(id) on delete set null;
create index if not exists clubs_federation_idx on clubs(federation_id);

-- federation_members (migration 006) linked an officer to a raw
-- application; link them to the structural node instead so capability
-- checks can walk the tree (a national officer has jurisdiction over every
-- state/district beneath them).
alter table federation_members add column if not exists federation_id bigint references federations(id) on delete set null;
create index if not exists fedmembers_federation_idx on federation_members(federation_id);
-- One office-holding row per (federation, user) — separate from migration
-- 006's unique(application_id, user_id), since older rows may have no
-- federation_id at all.
create unique index if not exists fedmembers_federation_user_idx on federation_members(federation_id, user_id) where federation_id is not null;
