-- Archery.Services — migration 028
-- Offline-first scoring, the two pieces ADR-0006/0007 promised but never
-- got built (docs/THREAT_MODEL.md T13, "Offline sync integrity", still
-- fully open — no "Status: fixed" line existed for it before this).
--
-- The `ends`/`arrows` schema (migration 021) already has everything a
-- correction needs — `superseded_by`, `correction_reason`, `actor` on
-- `arrows`, and `client_id` idempotency on both tables — but nothing in the
-- API ever wrote to those columns, and `ends` already carries a UNIQUE
-- constraint on (match_entry_id, end_number, shootoff_sequence) that
-- silently 500s (generic "Server error") the moment two devices submit
-- different arrow values for the same end. The constraint was already doing
-- its real job — no double-counted end can exist in computeMatchState's
-- SUM, since a second row for the same end_number can never be inserted —
-- it just had no graceful, judge-reviewable path when that happens for a
-- genuine reason (two scorers, two devices, a dropped connection resolved
-- twice). This migration adds the two structures that close that gap:
--
--   1. `ends.device_id` — which physical device recorded this end. Not an
--      account/actor (multiple people can share one login on one tablet);
--      a client-generated id persisted in that browser's localStorage. Lets
--      a judge reviewing a conflict actually see "phone A said 24, tablet B
--      said 26" rather than two anonymous submissions.
--   2. `scoring_conflicts` — append-only record of a genuine disagreement:
--      an end_number that was already recorded, with someone submitting a
--      DIFFERENT set of arrow values for it. Never auto-resolved. A judge
--      picks the correct value, which is written through the EXISTING
--      correction mechanism (a new `arrows` row, old row's superseded_by
--      set) — this table only tracks that a conflict happened and how it
--      was closed, it is not itself the source of truth for scores.

alter table ends add column if not exists device_id text;

create table if not exists scoring_conflicts (
  id                 bigint generated by default as identity primary key,
  match_entry_id     bigint not null references match_entries(id) on delete cascade,
  end_number         int not null,
  existing_end_id    bigint not null references ends(id) on delete cascade,
  -- The arrows that lost the race for the unique (match_entry_id,
  -- end_number, shootoff_sequence) slot. Stored as jsonb, not as real
  -- `arrows` rows — they were never accepted into the scoring domain, so
  -- they must never be summed by computeMatchState. This is the
  -- attempted-but-rejected submission, kept only for judge review.
  submitted_arrows   jsonb not null,
  submitted_client_id text,
  submitted_device_id text,
  submitted_by       text,               -- actor.name/username at submission time
  status             text not null default 'open' check (status in ('open','resolved')),
  resolved_by        text,
  resolution         text check (resolution in ('kept_existing','used_submitted','entered_new')),
  resolution_note    text,
  resolved_at        timestamptz,
  created_at         timestamptz not null default now()
);
create index if not exists scoring_conflicts_open_idx on scoring_conflicts(match_entry_id) where status = 'open';
