-- Archery.Services — migration 030
-- Para classification (DOMAIN.md §5: "Para is classification-first, not a
-- badge" — CLAUDE.md §3, docs/PLAN.md 2.7). Closes the gap migration 021's
-- own header flagged and left open on purpose: "categories has a para_class
-- column so the shape exists, but no classification workflow is built."
--
-- ⚠ CORRECTS A REAL ERROR IN THIS PROJECT'S OWN DOCUMENTATION. CLAUDE.md §3
-- and docs/DOMAIN.md both state "Para class — W1 | Open | VI1 | VI2 | VI3."
-- Fetched and read the actual primary source before writing this migration
-- (World Archery, "Para Archery Classification Rules and Regulations",
-- Version 2026-01-27, effective 2026-01-27 — the same rulebook edition
-- DOMAIN.md already cites for Book 3) — per CLAUDE.md §6: "if a primary
-- source contradicts this file... the primary source wins and you say so
-- out loud." Two things were wrong:
--   1. There is NO VI3. Appendix 2 §4.1: "There are two sport classes for
--      Visually Impaired athletes: VI1 [worse than LogMAR 2.6, blindfold +
--      spotter mandatory, §4.a] / VI2 [LogMAR 1.0–2.6, §5.a]."
--   2. "W1"/"Open" do not appear anywhere in this document. The physical-
--      impairment Sport Classes it actually defines are PI1 and PI2
--      (Appendix 1 §5.1.1/§5.1.2 — "W1"/"Open" may be informal or
--      competition-format names from a different, not-yet-sourced document;
--      asserting that mapping here would be inferring, not citing, so this
--      migration uses the classification document's own real codes).
-- The four real Sport Classes used below — PI1, PI2, VI1, VI2 — are the
-- ones an actual World Archery classification panel allocates. If a
-- separate competition-format source later confirms "W1"/"Open" as the
-- correct public-facing names for PI1/PI2, that is a display-label change
-- on top of these codes, not a reason to store an unverified code.
--
-- Modeled as request → adjudicate, the same pattern already used for
-- athlete_claim_requests / official_certifications (migration 024): the
-- platform does not perform the medical/functional assessment — a real
-- classification panel (Art. 7) does that, in person, over hours, using
-- diagnostic forms this platform never sees. What we record is the
-- ADJUDICATED OUTCOME (sport class + status), exactly the same posture this
-- codebase already takes for arrow values ("an adjudicated fact, not a
-- sensor reading") and shoot-off judge calls ("never computed").
--
-- Status enum mirrors the rulebook's real Sport Class Statuses (Art. 18-19)
-- collapsed to what actually matters for gating competition eligibility:
--   'confirmed'    = 'Confirmed (C)' (Art 19.1.1) — stable, no further review
--   'review_nao'   = 'Review at the Next Available Opportunity (R-NAO)' (19.1.2)
--   'review_frd'   = 'Review with a Fixed Review Date (R-FRD)' (19.1.3) —
--                    review_due_date typically <= 4 years out (19.1.3.3)
--   'expired'      = 'Expired (E)' (19.1.4) — Art 20.3: CANNOT compete until
--                    re-evaluated. 8 years' non-participation, retirement,
--                    or a missed fixed review date all lead here.
--   'not_eligible' = the two 'Not Eligible' designations (Art 13, 15) —
--                    collapsed into one platform status; the distinction
--                    between "no eligible impairment" and "does not meet
--                    minimum impairment criteria" is a classifier-facing
--                    reason, not something this platform's gate needs to
--                    branch on.
--   'pending'      = classification requested, not yet adjudicated (there
--                    is no 'New (N)' vs 'CNC' distinction kept here for the
--                    same reason — both just mean "cannot compete yet").
-- Only 'confirmed', 'review_nao', 'review_frd' allow entering a para
-- category — matching Art 20 (Confirmed/R-NAO/R-FRD may compete; Expired
-- may not until re-evaluated).

alter table categories drop constraint if exists categories_para_class_check;
alter table categories add constraint categories_para_class_check
  check (para_class in ('PI1','PI2','VI1','VI2'));

create table if not exists classification_requests (
  id                 bigint generated by default as identity primary key,
  athlete_id         bigint not null references athletes(id) on delete cascade,
  requested_by       bigint references users(id) on delete set null,
  sport_class_requested text not null check (sport_class_requested in ('PI1','PI2','VI1','VI2')),
  note               text,
  status             text not null default 'pending' check (status in ('pending','approved','rejected')),
  reviewed_by        text,
  reviewed_at        timestamptz,
  created_at         timestamptz not null default now()
);
create unique index if not exists classification_request_pending_idx
  on classification_requests(athlete_id) where status = 'pending';
create index if not exists classification_request_athlete_idx on classification_requests(athlete_id);

-- Append-only, like arrows: a reclassification is a NEW row, never an
-- overwrite of the old one (DOMAIN.md §3.1's "adjudicated fact" posture).
create table if not exists classifications (
  id                bigint generated by default as identity primary key,
  athlete_id        bigint not null references athletes(id) on delete cascade,
  sport_class       text not null check (sport_class in ('PI1','PI2','VI1','VI2')),
  status            text not null check (status in ('confirmed','review_nao','review_frd','expired','not_eligible','pending')),
  review_due_date   date,
  classified_by     text,        -- the real-world classification panel / classifier of record — not a platform user
  request_id        bigint references classification_requests(id) on delete set null,
  superseded_by     bigint references classifications(id),
  note              text,
  actor             text,        -- who recorded this row in OUR system (staff username/owner)
  created_at        timestamptz not null default now()
);
create index if not exists classifications_athlete_idx on classifications(athlete_id) where superseded_by is null;

-- Auto-expire: Art 19.1.4.1's "8 years' non-participation" and the fixed-
-- review-date rule both need a scheduled sweep in a real system; out of
-- scope here (no scheduler exists on this stack) — reviewers see
-- review_due_date directly instead, same honesty as anywhere else this
-- codebase declines to fabricate automation it hasn't built.
