-- Archery.Services — migration 031
-- Club & federation administration, closing two real gaps found while
-- surveying this session's build queue:
--   1. api/_handlers/federation.js (migration 026) is a fully built,
--      already-security-hardened hierarchy tree API — jurisdiction-scoped
--      officer capability, president-only appointment after an adversarial
--      audit caught a self-promotion bug — with ZERO UI reachability.
--      Nobody could actually use it. (No schema change needed for this
--      part; see admin.html/discover.html for the UI.)
--   2. club_members had no concept of a scoped "club admin" — every write
--      required GLOBAL staff access (owner/manager/editor/support), and
--      club membership was 100% staff-added with no self-service request
--      path at all (CLAUDE.md §3's "a club admin within a club" — a scoped
--      actor, not a global one — did not exist for clubs, only informally
--      for federations inside federation.js).
--
-- club_members.member_role had NO enforced CHECK constraint (just a
-- default + a comment claiming archer|coach|official) — tightened here
-- while adding 'admin', rather than leaving it open-ended.

alter table club_members drop constraint if exists club_members_member_role_check;
alter table club_members add constraint club_members_member_role_check
  check (member_role in ('archer','coach','official','admin'));

-- Self-service "join this club" request — same request→adjudicate shape as
-- athlete_claim_requests/official_certifications (migration 024). A club
-- ADMIN (member_role='admin', status='active' on that club) can approve
-- their own club's requests without needing global staff access; staff can
-- too, as a backstop (e.g. a club with no admin yet).
create table if not exists club_join_requests (
  id          bigint generated by default as identity primary key,
  club_id     bigint not null references clubs(id) on delete cascade,
  user_id     bigint not null references users(id) on delete cascade,
  discipline  text,
  note        text,
  status      text not null default 'pending' check (status in ('pending','approved','rejected')),
  reviewed_by text,
  reviewed_at timestamptz,
  created_at  timestamptz not null default now()
);
create unique index if not exists club_join_pending_idx
  on club_join_requests(club_id, user_id) where status = 'pending';
create index if not exists club_join_club_idx on club_join_requests(club_id) where status = 'pending';
