-- Archery.Services — migration 032
-- Coach licensing. Closes the gap docs/PLAN.md flagged: "consent-based
-- coach-athlete linking is real (migration 024)... licensing/certification
-- for coaches specifically... [is] not built." Today, calling yourself a
-- coach (`become-coach`) and getting one athlete to accept a link is the
-- entire vetting bar — no qualification is checked or shown anywhere.
--
-- A SEPARATE table from `official_certifications`, not a reuse of it: that
-- table is `unique(user_id)` — one certification row per person — because
-- it was built for judges/technical delegates, where holding two
-- certifications at once wasn't a real scenario. A coach can plausibly ALSO
-- be a certified judge; forcing both into one row would mean losing
-- whichever cert was set second. Same shape, same honesty as that table's
-- own header comment: "Levels are platform-defined administrative tiers,
-- not a World Archery citation" — coach accreditation levels are a
-- national-federation administrative matter (in India, the Archery
-- Association of India's coach education pathway), not a World Archery
-- technical rule the way scoring/classification are, so there is nothing
-- to cite an article number for here. Documented as platform policy.

create table if not exists coach_certifications (
  id            bigint generated by default as identity primary key,
  user_id       bigint not null references users(id) on delete cascade,
  level         text not null default 'club' check (level in ('club','state','national','international')),
  discipline    text,        -- optional specialisation: recurve|compound|barebow
  issuing_body  text,
  status        text not null default 'pending' check (status in ('pending','approved','revoked')),
  approved_by   text,
  approved_at   timestamptz,
  created_at    timestamptz not null default now(),
  unique(user_id)
);
