-- Archery.Services — migration 033
-- Anti-doping: the education-tracking half of docs/PLAN.md's "testing
-- pool, whereabouts, TUE workflow, education" line — deliberately ONLY the
-- education half. The other three are NOT built here, on purpose:
--
--   • TUE workflow — anti-doping.html already states, correctly, that "TUE
--     decisions are confidential medical/legal matters between an athlete
--     and their national anti-doping organisation" that this platform
--     "does not review, approve, or list." A Therapeutic Use Exemption is
--     decided by a qualified TUE Committee (WADA Code Art. 4.4) — a panel
--     of physicians with medical authority this platform's owner/manager
--     accounts do not have. Building a "staff approves this TUE" workflow,
--     even with good intentions, would put unqualified platform staff in
--     the position of adjudicating a medical exemption, and could mislead
--     an athlete into believing a real exemption exists when it doesn't.
--     That is a worse outcome than the honest empty state already there.
--   • Testing pool / whereabouts — Registered Testing Pool whereabouts
--     filing is REAL-TIME LOCATION DATA on athletes, submitted so doping
--     control officers can find them unannounced (ADAMS). Some of those
--     athletes are minors (CLAUDE.md §1.8). Building this responsibly needs
--     a real data-processing agreement with NADA/WADA, security review
--     matching that sensitivity, and a legal basis this platform does not
--     currently have. Building a version of it anyway — even labeled
--     "unofficial" — creates the exact risk it exists to prevent if it's
--     ever trusted or breached. Not built. Not a silent gap: said out loud
--     here per CLAUDE.md §6 ("when you find something worse than
--     documented, stop and say so").
--
-- What IS safe and real to build: (1) tracking which athletes have
-- completed the education modules already on anti-doping.html (currently
-- localStorage-only, lost on a new device/browser) — this makes no
-- doping-related determination, it's completion tracking, the same
-- shape as any other e-learning record; (2) letting a federation
-- designate a REAL anti-doping contact officer, reusing the
-- already-built, already-secured federation officer system (migration
-- 026/031) rather than inventing a new one — a federation president
-- assigns a real person, exactly as they already can for
-- president/secretary/treasurer/executive_member.

create table if not exists doping_education_progress (
  id           bigint generated by default as identity primary key,
  user_id      bigint not null references users(id) on delete cascade,
  module_id    text not null,   -- matches anti-doping.html's MODULES[].id — not enum-constrained here, the module list lives in the page, not the schema
  completed_at timestamptz not null default now(),
  unique(user_id, module_id)
);
create index if not exists doping_education_user_idx on doping_education_progress(user_id);
