-- Archery.Services — migration 034
-- Safeguarding: docs/PLAN.md's own words — "take this more seriously than
-- the shop. Background checks, incident reporting, mandatory-reporting
-- workflow, two-adult rules. guard-rail.html is a page where a policy
-- engine belongs." The report intake (POST /api/reports) was already real;
-- everything downstream of "a report arrived" was a two-state toggle
-- (open/reviewed) with no case ownership and no record of what was done.
--
-- Same judgment discipline as anti-doping (migration 033): recording that
-- a REAL, externally-verified background check/police verification exists
-- — who verified it, when, a reference number — is safe, the same posture
-- already used for official/coach certification and Para classification
-- (the platform transcribes a real external outcome, it doesn't produce
-- one). This migration does NOT attempt to perform, judge, or automate an
-- actual background check, and does NOT build a "mandatory reporting"
-- pipeline that files anything with police/child-protection authorities
-- automatically — that stays a human decision by whoever reviews a report,
-- exactly as guard-rail.html already correctly points urgent matters to
-- 112 / Childline 1098 directly, not through this platform.
--
-- club_members deliberately cannot identify minors at all (migration 013's
-- own DPDP-citing header) — clearance tracking below is scoped to
-- coach/official ACCOUNTS (users), not to club rosters, so it does not
-- cross that deliberately-drawn line.

alter table reports add column if not exists assigned_to text;
alter table reports add column if not exists resolution_note text;

-- Same shape as official_certifications (024) / coach_certifications (032):
-- self-declare, staff verifies, status/approved_by/approved_at. A person
-- could hold a coach license AND a safeguarding clearance AND a judge
-- cert simultaneously — same reasoning as coach licensing's own header for
-- why this is its own table rather than crammed into an existing one.
create table if not exists safeguarding_clearances (
  id                bigint generated by default as identity primary key,
  user_id           bigint not null references users(id) on delete cascade,
  clearance_type    text not null default 'background_check' check (clearance_type in ('background_check','police_verification','child_safety_training')),
  issuing_body      text,
  reference_number  text,
  status            text not null default 'pending' check (status in ('pending','approved','revoked')),
  approved_by       text,
  approved_at       timestamptz,
  created_at        timestamptz not null default now(),
  unique(user_id, clearance_type)
);
