-- Archery.Services — migration 039
-- Club practice sessions + attendance. Closes part of the gap
-- docs/PLAN.md / checkout-fee.js's Club/Range tier copy has advertised
-- since it was written: "class scheduling, attendance" — audited as not
-- built (migration 013's own header), still not built until now.
--
-- Deliberately a flat, standalone pair (mirrors `tournaments`'s shape, not
-- the deep events/event_categories/matches scoring-domain chain — a club
-- practice is not a sanctioned competition and doesn't need that model).
--
-- No date of birth or age column, matching club_members' own constraint
-- (migration 013: DPDP s.9(3) — a club roster does not carry minor PII).

create table if not exists club_sessions (
  id             bigint generated by default as identity primary key,
  club_id        bigint not null references clubs(id) on delete cascade,
  title          text not null,
  session_date   date not null,
  start_time     text,   -- free-text 'HH:MM' — a full tz-aware schedule is real
  end_time       text,   -- follow-on work; this is a v1 practice-session log.
  coach_user_id  bigint references users(id) on delete set null,
  notes          text,
  created_by     text,   -- actor label, same convention as club_join_requests.reviewed_by
  created_at     timestamptz not null default now()
);
create index if not exists club_sessions_club_idx on club_sessions(club_id, session_date desc);

create table if not exists club_attendance (
  id          bigint generated by default as identity primary key,
  session_id  bigint not null references club_sessions(id) on delete cascade,
  member_id   bigint not null references club_members(id) on delete cascade,
  status      text not null default 'present' check (status in ('present','absent','excused')),
  marked_by   text,
  marked_at   timestamptz not null default now(),
  unique (session_id, member_id)
);
