-- Archery.Services — migration 042
-- Federation communications board — closes the "communications board"
-- feature the district tier has advertised (checkout-fee.js) since it was
-- named and never built. A federation officer posts a real message scoped
-- to their federation node; every club (and its admins/coaches) under that
-- node can read it. Flat and standalone (mirrors club_sessions, migration
-- 039's own stated shape) — not a full inbox/thread system.

create table if not exists federation_messages (
  id             bigint generated by default as identity primary key,
  federation_id  bigint not null references federations(id) on delete cascade,
  title          text not null,
  body           text not null,
  posted_by      text,   -- actor label, same convention as club_sessions.created_by
  posted_by_user bigint references users(id) on delete set null,
  created_at     timestamptz not null default now()
);
create index if not exists federation_messages_fed_idx on federation_messages(federation_id, created_at desc);
