-- Archery.Services — migration 043
-- Consumer Protection (E-Commerce) Rules 2020 compliance. docs/PLAN.md
-- flagged this as "Currently: none implemented" — closing the three
-- concretely-specifiable pieces of it now:
--   Rule 4(4)(b): a published Grievance Officer, acknowledgement within 48
--     hours of receipt, resolution within one month.
--   Rule 5(f): country of origin disclosed per listing.
--   Rule 5: seller identity disclosure (this codebase already captures real
--     seller business_name/gst_number on `users` — migration 006 — the gap
--     was never DISPLAYING it on a listing; no schema change needed there).
--
-- Grievance Officer NAME/CONTACT is real business information this
-- migration cannot supply (CLAUDE.md §1.1 — never fabricate it) — it lives
-- in `settings` (grievanceOfficerName/Email/Phone/Address), same pattern as
-- platformGstin/platformLegalName/platformAddress, honestly rendered as
-- "not yet configured" until the owner fills it in via the admin panel.

alter table products add column if not exists country_of_origin text;

create table if not exists grievances (
  id                bigint generated by default as identity primary key,
  name              text not null,
  email             text not null,
  phone             text,
  order_no          text,
  subject           text not null,
  description       text not null,
  status            text not null default 'received' check (status in ('received','acknowledged','resolved','rejected')),
  filed_at          timestamptz not null default now(),
  acknowledged_at   timestamptz,
  resolved_at       timestamptz,
  resolution_notes  text,
  handled_by        text
);
create index if not exists grievances_status_idx on grievances(status, filed_at);
