-- Archery.Services — migration 044
-- Real product reviews, gated to VERIFIED PURCHASES only. product.html's
-- own comment (2026-07-16) already named this exact requirement: "Ratings
-- removed... there is no reviews table... Do not re-add a rating display
-- until real reviews exist." This is that table.
--
-- Orders are guest-checkout (no orders.user_id — only customer_email), so
-- "verified purchase" is checked by matching a logged-in reviewer's own
-- account email against a real PAID order's customer_email whose `items`
-- JSONB contains this product — computed at write time in
-- api/_handlers/reviews.js, never trusted from the client.

create table if not exists reviews (
  id           bigint generated by default as identity primary key,
  product_id   bigint not null references products(id) on delete cascade,
  user_id      bigint not null references users(id) on delete cascade,
  order_id     bigint not null references orders(id) on delete cascade,
  rating       int not null check (rating between 1 and 5),
  title        text,
  body         text,
  created_at   timestamptz not null default now(),
  unique (product_id, user_id)
);
create index if not exists reviews_product_idx on reviews(product_id, created_at desc);
