-- Archery.Services — migration 045
-- Real return/refund request tracking. refund-policy.html has promised a
-- process ("contact us with your order number... once the item passes
-- inspection, your refund is processed") since it was written, with zero
-- system behind it — no tracked state (orders_status_ck doesn't even have
-- a return/refund state), no admin workflow, purely an email-and-hope
-- process. This is the real infrastructure for that promise.
--
-- Deliberately does NOT call Razorpay's refund API — actually moving money
-- programmatically is its own, separately-deserved design/test pass (see
-- CLAUDE.md §1.10). This tracks the real request/decision lifecycle;
-- 'refunded' status records that a human processed the refund through
-- Razorpay's own dashboard, matched here by staff for a real audit trail —
-- it is not itself the trigger.

create table if not exists return_requests (
  id              bigint generated by default as identity primary key,
  order_id        bigint not null references orders(id) on delete cascade,
  reason          text not null,
  details         text,
  status          text not null default 'requested'
                    check (status in ('requested','approved','rejected','received','refunded')),
  refund_amount   numeric(10,2),
  requested_at    timestamptz not null default now(),
  decided_at      timestamptz,
  decided_by      text,
  notes           text
);
create index if not exists return_requests_order_idx on return_requests(order_id, requested_at desc);
create index if not exists return_requests_status_idx on return_requests(status, requested_at);
