-- Archery.Services — migration 046
-- Real product taxonomy. docs/PLAN.md: "Product taxonomy... or drop the
-- claim" — the WA-compliance half of that line was resolved 2026-08-13
-- (commit 1e5e142, the claim was dropped, not modelled — nothing in this
-- codebase can verify WA equipment compliance). This is the taxonomy half.
--
-- Before this: the 6 category values (Recurve Bows/Compound Bows/Arrows/
-- Targets/Accessories/Protective Gear) existed ONLY as hardcoded <option>
-- tags in admin.html and hardcoded button labels in shop.html — adding a
-- 7th category meant a code deploy, and nothing validated that
-- products.category (free text) actually matched one of the six. This
-- table doesn't invent new categories — it's the exact same six, now real
-- rows an admin can manage (rename, deactivate, reorder, add a new one)
-- without a deploy.

create table if not exists product_categories (
  id           bigint generated by default as identity primary key,
  name         text not null unique,
  icon         text,        -- matches product.html's CAT_META icon keys
  color        text,        -- matches product.html's CAT_META hex colors
  active       boolean not null default true,
  sort_order   int not null default 0,
  created_at   timestamptz not null default now()
);
insert into product_categories (name, icon, color, sort_order) values
  ('Recurve Bows','recurve','#C9A227',1),
  ('Compound Bows','compound','#22C55E',2),
  ('Arrows','arrows','#1F3E9C',3),
  ('Targets','target','#D22730',4),
  ('Accessories','tab','#F97316',5),
  ('Protective Gear','guard','#14B8A6',6)
on conflict (name) do nothing;
